### ISSUE TITLE
Timeout using MDATP (HTTPX)

### ISSUE THREAD

**Issue by Dajosue** [microsoft/msticpy#373]
Hello.
When I'm using MDATP and the timeout of HTTPX stop my search near to 5/6 seconds. 
Searching in the HTTPX documentation I found that HTTPX  may have a timeout predefined. Making my search so shorts.
To improve it, I recommend changing in the file "odata_driver.py"
URL (MSTICPy/data/drivers/odata_driver.py)

response = httpx.post(        
          url=req_url, headers=self.req_headers, content=str(body)    
)  

TO

response = httpx.post(        
          url=req_url, headers=self.req_headers, content=str(body) , **timeout=None**  
)  

Making the search more bigger, up to the API limit (max 100,000 rows).

Thank you.

**Comment by ianhelle** [comment]
We've done some fixes to this - changing default timeout to 30 sec connect, 10 sec other by default.
I think it would be a good idea to allow timeout as a query parameter - so that you can override individual query behaviour:
e.g.
```python
qry_prov.exec_query(query_text, timeout=30)
qry_prov.exec_query(query_text, timeout=(30,10))
qry_prov.exec_query(query_text, timeout=None)
```
We could also do this with the TI providers I think.
I also wanted to add the default as a global config setting - that may be a later bit of work but seems like a good idea vs. hard-coding it.

**Comment by ianhelle** [comment]
I've created a fix for this. 
The default behavior is httpx.Timeout(None).
This can be overridden in settings in msticpyconfig.yaml:
```yaml
http_timeout: 30           # = 30 sec timeout
http_timeout: [10, 30]   # = 30sec connect, 10sec other
http_timeout:                # specify individual param settings for httpx.Timeout
    connect: 30
    pool: 10
http_timeout: foo         # anything else = httpx.Timeout(None)
http_timeout: 
```

(some) query providers that use httpx can also override per-request by specifying a `timeout` parameter in the .connect() kwargs
or the query() kwargs
TI Providers also support this runtime parameter in either init or in lookup_ioc, lookup_iocs
